import { GoogleGenAI, Type } from "@google/genai";
import type { AnalysisResult, AnalysisData } from '../types';

// Fix: Per coding guidelines, the API key must be obtained exclusively from process.env.API_KEY. This resolves the error on import.meta.env.
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const analysisSchema = {
  type: Type.OBJECT,
  properties: {
    aiScore: {
      type: Type.NUMBER,
      description: 'A score from 0 to 100 representing the likelihood that the text was generated by an AI. 100 is definitively AI, 0 is definitively human.',
    },
    summary: {
      type: Type.STRING,
      description: 'A brief, one-sentence summary of the overall analysis, highlighting the most prominent AI or human-like characteristics found.'
    },
    analysis: {
      type: Type.ARRAY,
      description: 'A list of specific metrics analyzed in the text.',
      items: {
        type: Type.OBJECT,
        properties: {
          metric: {
            type: Type.STRING,
            description: 'The specific writing characteristic that was analyzed (e.g., "Burstiness", "Perplexity", "Repetition").'
          },
          finding: {
            type: Type.STRING,
            description: 'A detailed explanation of the finding for this metric. This should explain how the text performed and what it indicates about its origin (AI or human).'
          },
          score: {
            type: Type.NUMBER,
            description: 'A score from 0 to 100 for this specific metric, indicating how AI-like it appears. 100 is very AI-like.'
          }
        },
        required: ['metric', 'finding', 'score'],
      }
    },
    externalAnalysis: {
        type: Type.ARRAY,
        description: 'An analysis of how other common AI detection platforms might score the text. This is a prediction.',
        items: {
            type: Type.OBJECT,
            properties: {
                platformName: {
                    type: Type.STRING,
                    description: 'The name of the external platform (e.g., "ZeroGPT", "Copyleaks", "QuillBot").',
                    enum: ['ZeroGPT', 'QuillBot', 'Copyleaks']
                },
                predictedScore: {
                    type: Type.NUMBER,
                    description: 'The predicted score (0-100) that this platform might assign to the text, representing the percentage chance of AI generation.'
                },
                summary: {
                    type: Type.STRING,
                    description: 'A short, quoted summary of the platform\'s likely assessment, as if it were providing the result.'
                }
            },
            required: ['platformName', 'predictedScore', 'summary'],
        }
    }
  },
  required: ['aiScore', 'summary', 'analysis', 'externalAnalysis'],
};

const systemInstruction = `You are an expert AI content detector. Your task is to analyze user-submitted text and determine the likelihood that it was generated by a large language model.
Provide a detailed analysis based on several key metrics:
- **Perplexity**: How predictable and simple is the language? Lower perplexity often suggests AI generation.
- **Burstiness**: How varied are the sentence structures and lengths? Humans tend to write with more variation (high burstiness), while AI text can be more uniform.
- **Repetition**: Does the text reuse certain words or phrases unnaturally?
- **Vocabulary Richness**: How diverse is the vocabulary? AI can sometimes use a less varied or overly formal vocabulary.

For each piece of text, you must return a JSON object that strictly adheres to the provided schema. Do not add any extra text or formatting outside of the JSON object.
The main 'aiScore' should be your overall confidence score. The 'analysis' array should break down your reasoning. The 'externalAnalysis' should be your *prediction* of how other tools would score the text based on their typical detection patterns.`;

export const analyzeContent = async (text: string, mode: 'fast' | 'deep'): Promise<AnalysisResult> => {
  if (!text) {
    throw new Error("Content cannot be empty.");
  }
  
  const modelName = mode === 'fast' ? 'gemini-2.5-flash' : 'gemini-2.5-pro';

  try {
    const response = await ai.models.generateContent({
      model: modelName,
      contents: {
        parts: [{ text: `Please analyze the following text:\n\n---\n\n${text}` }]
      },
      config: {
        systemInstruction,
        responseMimeType: 'application/json',
        responseSchema: analysisSchema,
        temperature: 0.2,
      },
    });

    const jsonText = response.text.trim();
    const cleanJson = jsonText.replace(/^```json\s*|```\s*$/g, '');
    const result: AnalysisData = JSON.parse(cleanJson);
    return { data: result, content: text };

  } catch (error) {
    console.error("Error analyzing content with Gemini:", error);
    throw new Error("Failed to analyze content. The AI model may be experiencing issues.");
  }
};

export const rephraseContent = async (text: string, customPrompt?: string): Promise<string> => {
    if (!text) {
        throw new Error("Content to rephrase cannot be empty.");
    }

    const systemInstruction = `You are an expert content editor and copywriter. Your task is to rewrite the provided text.
Your primary goal is to instill a strong, authoritative, and distinctly human voice into the text.
The rephrased content should be engaging, clear, and natural.
Focus on varying sentence structure, using vivid language, and eliminating any robotic or overly formal phrasing.
The user will provide specific instructions. If they don't, your default goal is to make the text sound as human-written as possible, prioritizing a compelling and authentic voice over a low AI score.
Return ONLY the rephrased text, with no preamble or explanation.`;

    const userPrompt = customPrompt 
        ? `My specific instruction is: "${customPrompt}". Please apply this to the text below.`
        : `Please rephrase this text to make it sound as human-written as possible, giving it an engaging and authoritative voice.`;

    try {
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-pro',
            contents: {
                parts: [{ text: `${userPrompt}\n\n---\n\n${text}` }]
            },
            config: {
                systemInstruction,
                temperature: 0.9,
            },
        });
        
        return response.text.trim();
    } catch (error) {
        console.error("Error rephrasing content with Gemini:", error);
        throw new Error("Failed to rephrase content. The AI model may be experiencing issues.");
    }
};